from datetime import datetime, date
import re
from uuid import uuid4

from sqlalchemy import UUID, Column, DateTime, ForeignKey, MetaData, Numeric, String, Table, Date, Integer
from sqlalchemy.orm import declared_attr, Mapped, mapped_column, relationship


from .base_model import BaseSqlModel

class HouseNumber(BaseSqlModel):
    id: ...
    number: ...

class Street(BaseSqlModel):
    id: ...
    name: ...

class Country(BaseSqlModel):
    id: ...
    name: ...

class Region(BaseSqlModel):
    id: ...
    name: ...
    country_id: ...

class District(BaseSqlModel):
    id: ...
    name: ...
    region_id: ...

class SettlementType(BaseSqlModel):
    id: ...
    name: ...

class SettlementName(BaseSqlModel):
    id: ...
    name: ...
    district_id: ...
    settlement_type_id: ...

class StreetSettlementAssociation(BaseSqlModel):
    street_id: ...
    settlement_name_id: ...

class Address(BaseSqlModel):
    house_number_id: ...
    street_settlement_association_id: ...